### ISSUE TITLE
Misleading UI message is given if assign user script has failed

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm-app-shell#65]
A subscription is createted 
step1: click on  Subscription
step2: select a subscription and click tab User 
step3: click assign user
the assign user script failed.  A mail will be  send:
Dear user,

The user action for the subscription 'Shell(2)' has been finished but the related user action for the instance 'd10fea46-8ab2-4e01-a507-609273f3c082' failed. 

assign user failed because...

There may be an inconsistency between Catalog Manager, APP, and the application. Please check if the settings for the corresponding instance of the application were changed.

With best regards.

[observed]
![userassign](https://user-images.githubusercontent.com/15209605/53163880-5447ba00-35cf-11e9-8260-0da83458294d.PNG)

[expect]
the user will not be assigned

**Comment by GoebelL** [comment]
The user are assignement in this service is an asynchronous operation. UI is not designed to give feedback from the service. This is handled with email notification. Indeed this success message is a bit misleading since at this time the operation might even not be completed yet. I propose to change the success message.
Change the message "The users have been successfully assigned” to 
“The user assignment has been successfully triggered. Please check your email.”.

**Comment by Crystalzord** [comment]
Done in pull request: https://github.com/servicecatalog/oscm/pull/246
