### ISSUE TITLE
Persist internal parameters returned by provisioning script

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/oscm-app-shell#68]
**Summary**
Internal IDs or other parameters returned by provisioning script shall be persisted in APP-shell DB and passed back to the other scripts

**Details**
e.g. creating a VM in vCloud director provisioning script returns a VMID. This VMID shall be passed to the other scripts (update, operation, ...) to be used there.

**Comment by GoebelL** [comment]
AFAIK the returned paramater values are already persisted with the instance parameters in the APP database. It might require to expose this option with the Shall API provisioning script but at least the APP framework has foreseen such possibilities.
The other question is that existing instance parameter should be available to the scripts. The request is to expose all instance parameters in some form that the scripts can reference to them with variables, similar like service parameters. The instance parameter need a dedicated name or some prefix in the Shell API in order to distinguish them from provisioning settings, like service parameters or attriibutes.

**Comment by kowalczyka** [comment]
The only possible way to store newly-created parameters (as a result of script execution) seems to be

**Comment by kowalczyka** [comment]
The only possible way to store newly-created parameters (as a result of script execution) seems to be

**Comment by GoebelL** [comment]
Hi @kowalczyka 

you wrote
>and then accessible in other scripts as $INSTANCE_PARAM_KEY

You mean `${INSTANCE_PARAM_<KEY>}`, where `<KEY>` is the key of the parameter as returned in the JSON response, like above?
Or?

**Comment by kowalczyka** [comment]
1. I am just veryfing it but I found that instance parameters are already being included in the scripts as the part of provisioning settings, so it seems that we could simply access them with `${KEY}` where `KEY` is the key of the parameter as returned in the JSON response.

**Comment by kowalczyka** [comment]
After final changes, parameters which are persisted as a result of script execution (returned in the json output) are available in other scripts as `$SCRIPT_<KEY>`, where `<KEY>` is the key of the parameter as returned in the JSON response.
